path:
  PACKAGE_ROOT: classification_model
  TRAINED_DATASET_DIR: trained_models
  DATA: data

files:
  trained_model_name: classification_model
  version: 0.0.1

base:
  target_column: "survived"
  random_state: 0
  test_size: 0.2

model_params:
  C: 0.0005
  random_state: 0

data_source:
  openml: "https://www.openml.org/data/get_csv/16826755/phpMYEkMl"
  raw_data: raw_data/titanic_dataset.csv

attributes:
  cabin:
    - cabin
  numeric_variables:
    - "age"
    - "fare"
  categorical_variables:
    - "sex"
    - "cabin"
    - "embarked"
    - "title"
  drop_variables:
    - "name"
    - "ticket"
    - "boat"
    - "body"
    - "home.dest"

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: LogisticRegression
  run_name: mlops
  registered_model_name: LogisticRegressionModel
  remote_server_uri: http://localhost:5000